language: go

go:
 - "1.10.x"
 - "1.11.x"
 -  master

before_install:
  - go get -v ./core

script:
  - go test -v ./core -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
