language: go

go:
 - "1.10.2"

before_install:
  - go get -t -v ./...

script:
  - go test -v ./... -coverprofile=coverage.txt -covermode=atomic -timeout 0

after_success:
  - bash <(curl -s https://codecov.io/bash)
