language: go

go:
 - 1.11.x

env:
 - GO111MODULE=on

matrix:
  include:
    - script:
      - travis_retry go test -v ./... -coverprofile=coverage.txt -covermode=atomic
      after_success:
      - bash <(curl -s https://codecov.io/bash)
    - script:
      - travis_retry go test -v -tags='avx2' ./... -coverprofile=coverage.txt -covermode=atomic